api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            - { name: 'Authorization', type: 'apiKey', in: 'header' }
    title: 'Symfony API Platform'
    version: '1.0.0'
    show_webby: true
