
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false


    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native


    php_errors:
        log: true

    serializer:
        mapping:
            paths:
                - '%kernel.project_dir%/config/api_platform/serialization'
        enabled: true
        enable_annotations: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
